language: node_js
node_js:
  - 14
install:
  - npm install -g codecov
jobs:
  include:
  - stage: Tests & Coverage
    script:
    - cd client ; npm install
    - npm run coverage
    - cd ..
    - cd server ; npm install
    - npm run coverage &
    - npm start &
    - npm run testapi
    - cd ..
    - codecov
